Members allocation
Madson-Carvalho/Allocation-Manager-Be pull request #4
Opened 2024-10-23 23:05 UTC by GabriellMonteiro

2024-11-02 17:23 UTC, mateuskons approved these changes
Nice codification my friend.

2024-11-02 17:42 UTC, RodrigoTDonde approved these changes

2024-11-06 23:22 UTC, Madson-Carvalho commented on src/main/java/com/allocation/manager/controller/EmployeeController.java
> +class EmployeeController {
Voltar o public.

2024-11-06 23:45 UTC, Madson-Carvalho requested changes

2024-11-06 23:45 UTC, Madson-Carvalho commented on src/main/java/com/allocation/manager/model/ProjectEmployee.java
> +    public ProjectEmployee() {}
O construtor vazio tira.

2024-11-06 23:45 UTC, Madson-Carvalho commented on src/main/java/com/allocation/manager/service/impl/AllocationService.java
> +public class AllocationService implements IAllocationService {
Acrescentar o Impl a classe.

2024-11-06 23:45 UTC, Madson-Carvalho commented on src/main/java/com/allocation/manager/service/impl/EmployeeService.java
> +public class EmployeeService implements IEmployeeService {
Acrescentar o Impl a classe.

2024-11-06 23:45 UTC, Madson-Carvalho commented on src/main/java/com/allocation/manager/service/impl/ProjectService.java
> +public class ProjectService implements IProjectService {
Acrescentar o Impl a classe.

2024-11-07 23:04 UTC, merged